version: "3.8"

services:
 
  mysqldb:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysqldb
    restart: always
    healthcheck:
      test: "mysqladmin ping -h localhost -proot"
      timeout: 5s
      interval: 1m
      retries: 10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peer_tutor

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    depends_on:
      mysqldb:
        condition: service_healthy

  db-services-migrations-db:
    extends:
      file: ./backend/infra-local/backend.yml
      service: migrations
    ports:
      - 8191:3000
    depends_on:
      - phpmyadmin
    volumes:
      - ./backend/db/src:/app/src
      - ./backend/db/package.json:/app/package.json

  services:
    extends:
      file: ./backend/infra-local/backend.yml
      service: services
    ports:
      - 8501:3001
    depends_on:
      - db-services-migrations-db

  

 
    

