services:
  services:
    build:
      context: ./../services
      dockerfile: ./Dockerfile
    volumes:
      - ./../services/src:/services/src
    restart: always
    command: npm run start:dev

  migrations:
    build:
      context: ./../db
      dockerfile: ./Dockerfile

    volumes:
      - ./../db/src:/app/src
      - ./../db/package.json:/app/package.json
